[project]
name = "hamish-bot"
version = "0.1.0"
description = "Bot scripts on Wikimedia / Not Reliable"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymysql>=1.1.1",
    "pywikibot>=10.2.0",
    "toolforge>=6.1.0",
]
